name: Deploy Staging API

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Staging API
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Run App
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /root/mabar-fun
            git checkout development
            git pull origin development
            pnpm install
            pnpm build --filter=db
            pnpm build --filter=server
            pnpm turbo run db:deploy --filter=db
            pm2 start 0
